### ISSUE TITLE
It is not working.

### ISSUE THREAD

**Issue by firatcetiner** [datvo0110/flutter_tab_bar_no_ripple#1]
Tried your example and it is not working. The ripple is still there.

**Comment by maheshperi19** [comment]
I have checked it. Example project is not working, but i installed package directly into my app and checked. It is working fine. But need to change icon color and text colors of tabs. Otherwise it will show like white page.

Tab(
                child: Text(
                  page.text,
                  style: CustomTextStyle.customTitleWithBoldFont(
                      context: context, textColor: kBlackColor, fontSize: 18),
                ),
                icon: Icon(
                  page.icon,
                  color: kBlackColor,
                ));

**Comment by thanhdatvo** [comment]
@MaheshPeri19 @firatcetiner Hi, because I implemented this feature a long time ago, it may be out of date, I will update it
